### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by champierre** [Romotive/Romo#2]
Looks like files under RMCore > Communication > FirmwareCommon are missing.

![2015-08-07 17 28 21](https://cloud.githubusercontent.com/assets/10215/9131898/9b11f8e8-3d2a-11e5-8fac-0f66a21064cf.png)

![2015-08-07 17 28 02](https://cloud.githubusercontent.com/assets/10215/9131896/9a044a0a-3d2a-11e5-9a58-3cfa1890c978.png)

**Comment by sweetleon** [comment]
I'm seeing the same problem :-1:

**Comment by sweetleon** [comment]
@roksenhorn I realize this is unsupported, but would it be possible to add the missing files from `RMCore > Communication > FirmwareCommon`? Thanks!

**Comment by roksenhorn** [comment]
Working on a fix...

**Comment by roksenhorn** [comment]
@sweetleon @champierre  Pull master to get the fix!
